apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-pod
  labels:
    component: spring-boot
spec:
  containers:
    - name: client
      image: manujgupta25/springbootmongo:V1.0
      ports:
        - containerPort: 8000
      env:
        - name: MONGODB_HOST
          value: spring-boot-mongo