apiVersion: v1
kind: Service
metadata:
  name: spring-boot-client
  labels:
    component: spring-boot-client
spec:
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31515
  selector:
    component: spring-boot
  type: NodePort